### ISSUE TITLE
Explain purpose

### ISSUE THREAD

**Issue by rawtaz** [hmps/neat#1]
This might be a silly question, but what is the purpose of this package/component, considering there's already (the seemingly more official) https://github.com/thoughtbot/neat in the Bower repository? They both seem to carry the latest version of Neat.

Whatever the answer is, it would be great if you could write a little about it in the README. Thanks!

**Comment by tysongach** [comment]
@hmps This fork of Neat and its package on Bower is out-of-date. [Neat](https://github.com/thoughtbot/neat)—the original project—is already published on Bower. Would you be up for removing this package from Bower to prevent confusion and better point people to the main Neat source?

**Comment by hmps** [comment]
@tysongach thanks for giving me a heads up here. I had completely forgotten about adding this to Bower. I have removed it now and will delete this repo shortly.

**Comment by tysongach** [comment]
@hmps Great, thank you!
